import { BOOK_ENTITY_KINDS } from '@worldbookllm/shared';

import { ReadOnlyBookPathError } from '../errors.js';
import { classifyBookPath } from './book-paths.js';

/**
 * File kinds whose edits change what `story reindex` writes into the
 * registries (entity titles and fields, the story title), so a direct edit
 * reindexes in the same change.
 */
const REINDEXED_KINDS = new Set<string>([...BOOK_ENTITY_KINDS, 'story']);

export function needsReindex(path: string): boolean {
  return REINDEXED_KINDS.has(classifyBookPath(path).kind);
}

/**
 * Files the app may write directly: Markdown only, never a generated
 * registry (those come from `story reindex`) and never into `dist/`.
 */
export function assertWritablePath(path: string): void {
  if (!path.endsWith('.md'))
    throw new ReadOnlyBookPathError(path, 'only Markdown files are edited');
  if (path === 'dist' || path.startsWith('dist/')) {
    throw new ReadOnlyBookPathError(path, 'dist/ holds build output');
  }
  if (classifyBookPath(path).kind === 'registry') {
    throw new ReadOnlyBookPathError(path, 'registries are generated by story reindex');
  }
}
